[build]
  command = "npm run build" # Adjust this command based on your build process
  publish = "build"        # The directory where the built React app is located

[[redirects]]
  from = "/*"
  to = "/firstpage/main.html" # Adjust the path to your index.html
  status = 200
